// Use a query like this as a condition in an alert on failed keyvault operations

traces
| where timestamp > ago(1d)
| where customDimensions.eventId in ('RT0015', 'RT0017')
| project timestamp
, extensionName = customDimensions.extensionName
, extensionId = customDimensions.extensionId
, extensionPublisher = customDimensions.extensionPublisher
, extensionVersion = customDimensions.extensionVersion
, failureReason = customDimensions.failureReason
, message