// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT License. See License.txt in the project root for license information. 
// ------------------------------------------------------------------------------------------------

enum 50183 BlobPublicAccess
{
    value(0; private) { }
    value(1; container) { }
    value(2; blob) { }
}