//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCCompressionCli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCCompressionCli.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOCOUNT ON
        ///BEGIN
        ///
        ///DECLARE @compress_method sysname
        ///SELECT @compress_method = &apos;PAGE&apos;
        ///DECLARE @schema_name sysname, @table_name sysname, @used_mb sysname, @allocated_mb sysname
        ///CREATE TABLE #compress_report_tb 
        ///(ObjName sysname,
        ///schemaName sysname,
        ///indx_ID int,
        ///partit_number int,
        ///size_with_current_compression_setting bigint,
        ///size_with_requested_compression_setting bigint,
        ///sample_size_with_current_compression_setting bigint,
        ///sample_size_with_requested_compression_setting bigint)
        ///
        ///DECLARE c_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompressionReport {
            get {
                return ResourceManager.GetString("CompressionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top {0} tab.name as [table], 
        ///    cast(sum(spc.used_pages * 8)/1024.00 as numeric(36, 2)) as used_mb,
        ///    cast(sum(spc.total_pages * 8)/1024.00 as numeric(36, 2)) as allocated_mb
        ///from sys.tables tab
        ///join sys.indexes ind 
        ///     on tab.object_id = ind.object_id
        ///join sys.partitions part 
        ///     on ind.object_id = part.object_id and ind.index_id = part.index_id
        ///join sys.allocation_units spc
        ///     on part.partition_id = spc.container_id
        ///where tab.name &lt;&gt; &apos;Application Object Metadata&apos;
        ///group by tab.n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectTopNBigTables {
            get {
                return ResourceManager.GetString("SelectTopNBigTables", resourceCulture);
            }
        }
    }
}
