let
    Source = #table( type table [ MonthNumber = Int64.Type ], List.Split({1..12},1)),
    Translations = Table.AddColumn( Source, "Translations",
        each
          [ MonthDate = #date( 2022, [ MonthNumber ], 1 ),
            Translations = List.Transform(Languages[DefaultCulture], each Date.MonthName( MonthDate, _ ) ),
            TranslationTable = Table.FromList( Translations, null ),
            TranslationsTranspose = Table.Transpose(TranslationTable),
            TranslationsColumns = Table.RenameColumns(
              TranslationsTranspose,
              List.Zip({ Table.ColumnNames( TranslationsTranspose ), 
                         List.Transform(Languages[Language], 
                         each "MonthNameTranslations" & _ ) })
            )
          ]
    ),
    ExpandedTranslations = Table.ExpandRecordColumn(Translations, 
                                                    "Translations", 
                                                    { "TranslationsColumns" }, 
                                                    { "TranslationsColumns" }),
    ColumnsCollection = List.Transform(Languages[Language], each "MonthNameTranslations" & _ ),
    ExpandedTranslationsColumns = Table.ExpandTableColumn(ExpandedTranslations, 
                                                          "TranslationsColumns", 
                                                          ColumnsCollection, 
                                                          ColumnsCollection ),
    TypedColumnsCollection = List.Transform(ColumnsCollection, each {_, type text}),
    QueryOutput = Table.TransformColumnTypes(ExpandedTranslationsColumns, TypedColumnsCollection)
in
    QueryOutput
